<?php
/**
 * The spreadsheet column headings GL Assessment use for each assessment type.
 *
 * A mapping offers these as the choices for a field, so a school picks a
 * heading rather than typing one.
 *
 * @category Module
 * @package  Gibbon\Module\AcademicRecords
 * @author   Steve Gillott
 * @license  https://www.gnu.org/licenses/gpl-3.0.html GNU GPL v3
 * @version  GIT: $Id$
 * @link     https://gibbonedu.org
 */

namespace Gibbon\Module\AcademicRecords\CAT4;

class HeaderSets
{
    /**
     * Headings keyed by assessment type.
     *
     * @return array<string,array<int,string>>
     */
    public static function all(): array
    {
        return [
            'cat4_scores' => explode(',', 'Verbal SAS,Quantitative SAS,Non-verbal SAS,Spatial SAS,Mean SAS'),
        
            'ks3' => explode(',', 'KS3 English level,KS3 English level if challenged,KS3 Maths level,KS3 Maths level if challenged,KS3 Science level,KS3 Science level if challenged,KS3 Art Level,KS3 Art Level if challenged,KS3 D&T Level,KS3 D&T Level if challenged,KS3 Geography Level,KS3 Geography Level if challenged,KS3 History Level,KS3 History Level if challenged,KS3 ICT Level,KS3 ICT Level if challenged,KS3 MFL Level,KS3 MFL Level if challenged,KS3 Music Level,KS3 Music Level if challenged,KS3 PE Level,KS3 PE Level if challenged,KS3 English point score,KS3 English point score if challenged,KS3 Maths point score,KS3 Maths point score if challenged,KS3 Science point score,KS3 Science point score if challenged,KS3 Art point score,KS3 Art point score if challenged,KS3 D&T point score,KS3 D&T point score if challenged,KS3 Geography point score,KS3 Geography point score if challenged,KS3 History point score,KS3 History point score if challenged,KS3 ICT point score,KS3 ICT point score if challenged,KS3 MFL point score,KS3 MFL point score if challenged,KS3 Music point score,KS3 Music point score if challenged,KS3 PE point score,KS3 PE point score if challenged,KS3 English fine level,KS3 English fine level if challenged,KS3 Maths fine level,KS3 Maths fine level if challenged,KS3 Science fine level,KS3 Science fine level if challenged,KS3 Art fine level,KS3 Art fine level if challenged,KS3 D&T fine level,KS3 D&T fine level if challenged,KS3 Geography fine level,KS3 Geography fine level if challenged,KS3 History fine level,KS3 History fine level if challenged,KS3 ICT fine level,KS3 ICT fine level if challenged,KS3 MFL fine level,KS3 MFL fine level if challenged,KS3 Music fine level,KS3 Music fine level if challenged,KS3 PE fine level,KS3 PE fine level if challenged'),
        
            'gcse_grade' => explode(',', 'GCSE Art & Design grade,GCSE Art & Design grade if challenged,GCSE Biology grade,GCSE Biology grade if challenged,GCSE Business Studies grade,GCSE Business Studies grade if challenged,GCSE Chemistry grade,GCSE Chemistry grade if challenged,GCSE Citizenship Studies grade,GCSE Citizenship Studies grade if challenged,GCSE Computer Science grade,GCSE Computer Science grade if challenged,GCSE Design & Technology grade,GCSE Design & Technology grade if challenged,GCSE Drama grade,GCSE Drama grade if challenged,GCSE English Language grade,GCSE English Language grade if challenged,GCSE English Literature grade,GCSE English Literature grade if challenged,GCSE Food preparation and nutrition grade,GCSE Food preparation and nutrition grade if challenged,GCSE French grade,GCSE French grade if challenged,GCSE Geography grade,GCSE Geography grade if challenged,GCSE German grade,GCSE German grade if challenged,GCSE History grade,GCSE History grade if challenged,GCSE ICT grade,GCSE ICT grade if challenged,GCSE Maths grade,GCSE Maths grade if challenged,GCSE Media Studies grade,GCSE Media Studies grade if challenged,GCSE Music grade,GCSE Music grade if challenged,GCSE Physical Education grade,GCSE Physical Education grade if challenged,GCSE Physics grade,GCSE Physics grade if challenged,GCSE Religious Studies grade,GCSE Religious Studies grade if challenged,GCSE Science Combined grade,GCSE Science Combined grade if challenged,GCSE Sociology grade,GCSE Sociology grade if challenged,GCSE Spanish grade,GCSE Spanish grade if challenged,GCSE Statistics grade,GCSE Statistics grade if challenged'),
        
            'gcse_points' => explode(',', 'GCSE Art & Design points scale,GCSE Art & Design points scale if challenged,GCSE Biology points scale,GCSE Biology points scale if challenged,GCSE Business Studies points scale,GCSE Business Studies points scale if challenged,GCSE Chemistry points scale,GCSE Chemistry points scale if challenged,GCSE Citizenship Studies points scale,GCSE Citizenship Studies points scale if challenged,GCSE Computer Science points scale,GCSE Computer Science points scale if challenged,GCSE Design & Technology points scale,GCSE Design & Technology points scale if challenged,GCSE Drama points scale,GCSE Drama points scale if challenged,GCSE English Language points scale,GCSE English Language points scale if challenged,GCSE English Literature points scale,GCSE English Literature points scale if challenged,GCSE Food preparation and nutrition points scale,GCSE Food preparation and nutrition points scale if challenged,GCSE French points scale,GCSE French points scale if challenged,GCSE Geography points scale,GCSE Geography points scale if challenged,GCSE German points scale,GCSE German points scale if challenged,GCSE History points scale,GCSE History points scale if challenged,GCSE ICT points scale,GCSE ICT points scale if challenged,GCSE Maths points scale,GCSE Maths points scale if challenged,GCSE Media Studies points scale,GCSE Media Studies points scale if challenged,GCSE Music points scale,GCSE Music points scale if challenged,GCSE Physical Education points scale,GCSE Physical Education points scale if challenged,GCSE Physics points scale,GCSE Physics points scale if challenged,GCSE Religious Studies points scale,GCSE Religious Studies points scale if challenged,GCSE Science Combined points scale,GCSE Science Combined points scale if challenged,GCSE Sociology points scale,GCSE Sociology points scale if challenged,GCSE Spanish points scale,GCSE Spanish points scale if challenged,GCSE Statistics points scale,GCSE Statistics points scale if challenged'),
        
            'aslevel' => explode(',', 'AS Accounting,AS Accounting if challenged,AS Art and Design,AS Art and Design if challenged,AS Biology,AS Biology if challenged,AS Business Studies,AS Business Studies if challenged,AS Chemistry,AS Chemistry if challenged,AS Computer Science,AS Computer Science if challenged,AS Critical Thinking,AS Critical Thinking if challenged,AS Design and Technology,AS Design and Technology if challenged,AS Drama and Theatre,AS Drama and Theatre if challenged,AS Economics,AS Economics if challenged,AS English Language,AS English Language if challenged,AS English Literature,AS English Literature if challenged,AS Finance,AS Finance if challenged,AS French,AS French if challenged,AS Geography,AS Geography if challenged,AS Government and Politics,AS Government and Politics if challenged,AS History,AS History if challenged,AS Law,AS Law if challenged,AS Maths,AS Maths if challenged,AS Media Studies,AS Media Studies if challenged,AS Physical Education,AS Physical Education if challenged,AS Physics,AS Physics if challenged,AS Psychology,AS Psychology if challenged,AS Religious Studies,AS Religious Studies if challenged,AS Sociology,AS Sociology if challenged,AS Spanish,AS Spanish if challenged'),
        
            'alevel' => explode(',', 'A Art and Design,A Art and Design if challenged,A Biology,A Biology if challenged,A Business Studies,A Business Studies if challenged,A Chemistry,A Chemistry if challenged,A Classical Civilisation,A Classical Civilisation if challenged,A Computer Science,A Computer Science if challenged,A Design and Technology,A Design and Technology if challenged,A Drama and Theatre,A Drama and Theatre if challenged,A Economics,A Economics if challenged,A English Language,A English Language if challenged,A English Literature,A English Literature if challenged,A French,A French if challenged,A Geography,A Geography if challenged,A Government and Politics,A Government and Politics if challenged,A History,A History if challenged,A Law,A Law if challenged,A Maths,A Maths if challenged,A Media Studies,A Media Studies if challenged,A Music,A Music if challenged,A Physical Education,A Physical Education if challenged,A Physics,A Physics if challenged,A Psychology,A Psychology if challenged,A Religious Studies,A Religious Studies if challenged,A Sociology,A Sociology if challenged'),
        
            'myp' => explode(',', 'IB MYP Arts,IB MYP Arts if challenged,IB MYP English,IB MYP English if challenged,IB MYP French,IB MYP French if challenged,IB MYP German,IB MYP German if challenged,IB MYP Humanities,IB MYP Humanities if challenged,IB MYP Mathematics,IB MYP Mathematics if challenged,IB MYP Physical Education,IB MYP Physical Education if challenged,IB MYP Sciences,IB MYP Sciences if challenged,IB MYP Spanish,IB MYP Spanish if challenged,IB MYP Technology,IB MYP Technology if challenged'),
        
            'ibdp' => explode(',', 'Total IB Diploma Points,Total IB Diploma Points if challenged,IB DP G1 Studies in language and literature HL,IB DP G1 Studies in language and literature HL if challenged,IB DP G1 Studies in language and literature SL,IB DP G1 Studies in language and literature SL if challenged,IB DP G2 Language acquisition HL,IB DP G2 Language acquisition HL if challenged,IB DP G2 Language acquisition SL,IB DP G2 Language acquisition SL if challenged,IB DP G3 Individuals and societies HL,IB DP G3 Individuals and societies HL if challenged,IB DP G3 Individuals and societies SL,IB DP G3 Individuals and societies SL if challenged,IB DP G4 Sciences HL,IB DP G4 Sciences HL if challenged,IB DP G4 Sciences SL,IB DP G4 Sciences SL if challenged,IB DP G5 Mathematics HL,IB DP G5 Mathematics HL if challenged,IB DP G5 Mathematics SL,IB DP G5 Mathematics SL if challenged,IB DP Biology,IB DP Biology if challenged,IB DP Business and Management,IB DP Business and Management if challenged,IB DP Chemistry,IB DP Chemistry if challenged,IB DP English,IB DP English if challenged,IB DP Film,IB DP Film if challenged,IB DP French,IB DP French if challenged,IB DP Geography,IB DP Geography if challenged,IB DP History,IB DP History if challenged,IB DP Maths HL,IB DP Maths HL if challenged,IB DP Maths SL,IB DP Maths SL if challenged,IB DP Physics,IB DP Physics if challenged,IB DP Psychology,IB DP Psychology if challenged,IB DP Theatre Studies,IB DP Theatre Studies if challenged,IB DP Theory of Knowledge,IB DP Theory of Knowledge if challenged,IB DP Visual Arts,IB DP Visual Arts if challenged,IB DP World Religions,IB DP World Religions if challenged'),
        ];
    }
}
